import {
  Home as HomeIcon,
  Assessment as AssessmentIcon,
  ExitToApp as LogOutIcon,
  Timeline as TimelineIcon,
  AddBox as AddBoxIcon,
  FindInPage as FindInPageIcon,
  ExpandLess,
  ExpandMore,
  AccountCircle as UserIcon,
  MonetizationOn as VentasIcon,
  ContactMail as PlanesIcon,
  ViewQuilt as DasboardIcon,
  FolderShared as ClienteIcon,
  Description as ReporteIcon,
  Work as EmpleadoIcon,
  ViewList as InventarioIcon,
  Archive as ProductoIcon,
  ShoppingBasket as ComprasIcon,
  AirlineSeatFlat as DifuntoIcon,
  HowToReg as SuscripcionIcon,
  WatchLater as MensualidadIcon,
  PeopleAlt as ParienteIcon,
} from '@material-ui/icons';

export {
  HomeIcon,
  AssessmentIcon,
  LogOutIcon,
  TimelineIcon,
  AddBoxIcon,
  FindInPageIcon,
  ExpandLess,
  ExpandMore,
  UserIcon,
  VentasIcon,
  PlanesIcon,
  DasboardIcon,
  ClienteIcon,
  ReporteIcon,
  EmpleadoIcon,
  ProductoIcon,
  InventarioIcon,
  ComprasIcon,
  DifuntoIcon,
  SuscripcionIcon,
  MensualidadIcon,
  ParienteIcon,
};
