import {
  Home as HomeIcon,
  Assessment as AssessmentIcon,
  ExitToApp as LogOutIcon,
  Timeline as TimelineIcon,
  AddBox as AddBoxIcon,
  FindInPage as FindInPageIcon,
  ExpandLess,
  ExpandMore,
  AccountCircle as UserIcon,
  MonetizationOn as VentasIcon,
  ContactMail as PlanesIcon,
  ViewQuilt as DasboardIcon,
  SupervisedUserCircle as ClienteIcon,
  Description as ReporteIcon,
  Work as EmpleadoIcon,
  ShoppingBasket as ProductoIcon,
  ViewList as InventarioIcon,
} from '@material-ui/icons';

export {
  HomeIcon,
  AssessmentIcon,
  LogOutIcon,
  TimelineIcon,
  AddBoxIcon,
  FindInPageIcon,
  ExpandLess,
  ExpandMore,
  UserIcon,
  VentasIcon,
  PlanesIcon,
  DasboardIcon,
  ClienteIcon,
  ReporteIcon,
  EmpleadoIcon,
  ProductoIcon,
  InventarioIcon,
};
